version: 2.1

orbs:
  node: circleci/node@4.1
  netlify: circleci/netlify@1.0.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages

workflows:
  build-deploy:
    jobs:
      - build
      - netlify/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
